[package]
name = "flashrom"
version = "0.1.0"
description = "GUI utility for safer Android ADB/Fastboot workflows"
authors = ["Võ Xuân Dương"]
edition = "2021"

[lib]
name = "flashrom_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
tauri = { version = "2", features = [] }
